# Generated by Django 4.0.6 on 2023-07-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplayer', '0002_uploadmovie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmovie',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
